### ISSUE TITLE
Practica 1 Mockup

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/practicaprototipos-equipo-topicos-as#3]
Proyecto figma (Mockup)
https://www.figma.com/file/EIkAMlagJizWPeoMgFbopP/EQUIPO-BGWR?type=design&node-id=0-1&mode=design&t=XxHDl96f2y26jRV9-0
PDF(reporte de prectica)
https://drive.google.com/file/d/1lKN-ogb-PObpfMMfSTU9btjeHqQBWA4w/view?usp=drive_link

**Comment by HECTOR-KDM02** [comment]
Como equipo designado a la calificar este trabajo y basándonos en el criterio del docente en la mayoría de los apartados esta correctamente explicado y queda claro sin embargo en el apartado 3 (Figuras, ilustraciones y fotografías.) pese a que tienen la explicación de 10 paneles 8 botones y 2 imágenes de explicación sobre el acceso solo pudimos detectar 10 imágenes en cuestión así que como equipo decidimos de manera unánime colocar:


calificación de 95

**Comment by josealfredo79** [comment]
![image](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-topicos-as/assets/58342642/dd795a97-979a-4252-877d-35ff3d0510bb)
En esta ventana ponlo alineado la etiqueta Carrera a la izquierda por favor... @williamgl3

**Comment by josealfredo79** [comment]
Calificacion 19 Bien hecho y realizado...por favor atender los detalles..gracias...
